#!/bin/bash -x

set +e

URL="http://downloads.arduino.cc/arduino-nightly-linux64.tar.xz"
APP=Arduino
mkdir -p ./$APP/$APP.AppDir
cd ./$APP

wget -c "$URL"

tar xf *.tar.xz
mv ardu*/* $APP.AppDir

cd $APP.AppDir/

mv arduino AppRun
cp lib/arduino_small.png arduino.png
sed -i -e 's|FULL_PATH/||g' arduino.desktop

cd ..

# Figure out $VERSION
VER=$(grep -r ARDUINO $APP.AppDir/revisions.txt | head -n 1 | cut -d " " -f 2)
HOUR=$(cat $APP.AppDir/lib/hourlyBuild.txt | sed -e 's|/||g' | sed -e 's| ||g' | sed -e 's|:||g')
VERSION=$VER"_"$HOUR
echo $VERSION

wget -c "https://github.com/probonopd/AppImageKit/releases/download/4/AppImageAssistant" # (64-bit)
chmod a+x ./AppImageAssistant
./AppImageAssistant ./$APP.AppDir/ ../out/$APP"-"$VERSION"-x86_64.AppImage"
