#!/bin/bash -x

set +e

URL="http://downloads.arduino.cc/arduino-nightly-linux64.tar.xz"
APP=Arduino
mkdir -p ./$APP
cd ./$APP

wget -c "$URL"

tar xf *.tar.xz
mv ardu*/ $APP.AppDir

cd $APP.AppDir/

mv arduino AppRun
cp lib/arduino_small.png arduino.png
sed -i -e 's|FULL_PATH/||g' arduino.desktop

# Move icons into place so that AppImageAssistant finds them
mkdir -p usr/share/icons/
mv lib/icons/ usr/share/icons/hicolor
cat usr/share/icons/hicolor/96x96/apps/arduino.png > arduino.png

# Get appdata - why is it missing in the binary distribution?
mkdir -p usr/share/appdata/
rm usr/share/appdata/arduino.appdata.xml || true
wget -c "https://github.com/arduino/Arduino/raw/master/build/linux/dist/appdata.xml" -O usr/share/appdata/arduino.appdata.xml

# Get desktop file
mv lib/desktop.template arduino.desktop
sed -i -e 's/<BINARY_LOCATION>/AppRun/g' arduino.desktop
sed -i -e 's/<ICON_NAME>/arduino/g' arduino.desktop

# Add git version of https://github.com/esp8266/Arduino/
git clone https://github.com/esp8266/Arduino.git hardware/esp8266/git/ 
cd hardware/esp8266/git/tools/
python ./get.py
ESPVER=$(git rev-list --count HEAD)
sed -i  -r "s|^name=.*?|name=ESP8266 Modules (git $ESPVER)|g" ../platform.txt
cd ../../../../

cd ..

# Figure out $VERSION
VER=$(grep -r ARDUINO $APP.AppDir/revisions.txt | head -n 1 | cut -d " " -f 2)
HOUR=$(cat $APP.AppDir/lib/hourlyBuild.txt | sed -e 's|/||g' | sed -e 's| ||g' | sed -e 's|:||g')
VERSION=$VER"."$HOUR".esp"$ESPVER
echo $VERSION

wget -c "https://github.com/probonopd/AppImageKit/releases/download/5/AppImageAssistant" # (64-bit)
chmod a+x ./AppImageAssistant
mkdir -p ../out
rm ../out/$APP"-"$VERSION"-x86_64.AppImage" || true
./AppImageAssistant ./$APP.AppDir/ ../out/$APP"-"$VERSION"-x86_64.AppImage"
