#!/bin/bash -x

# We do not have to build this ourselves since the upstream project 
# does a great job in providing binaries that run on a great number of systems
# other upstream projects could learn from Mozilla - how do they do it?

set +e

wget -q https://github.com/probonopd/AppImages/raw/master/functions.sh -O ./functions.sh
. ./functions.sh

APP=Thunderbird
LOWERAPP=${APP,,} 

mkdir -p ./$APP/$APP.AppDir/usr
cd ./$APP

wget -c --trust-server-names "https://download.mozilla.org/?product=thunderbird-latest&os=linux64"
VER1=$(ls thunderbird-*.tar.bz2 | cut -d "-" -f 2 | sed -e 's|.tar.bz2||g')

cd ./$APP.AppDir
tar xfj ../*.tar.bz2

mv thunderbird usr/bin

find . -name default256.png -exec cp \{\} thunderbird.png \;

cat > thunderbird.desktop <<EOF
[Desktop Entry]
Type=Application
Name=Thunderbird Mail
Icon=thunderbird
Exec=thunderbird %u
Categories=Application;Office;Network;Email;
MimeType=x-scheme-handler/mailto;application/x-xpinstall;
StartupNotify=true
EOF

get_apprun

# Thunderbird does not ship with appdata yet so we use
# information that we got on Fedora from
# appstreamcli dump thunderbird.desktop
mkdir -p usr/share/appdata/
cat > usr/share/appdata/thunderbird.appdata.xml <<\EOF
<?xml version="1.0" encoding="utf-8"?>
<component type="desktop">
  <id>thunderbird.desktop</id>
  <name>Thunderbird Mail</name>
  <summary>Send and receive mail with Thunderbird</summary>
  <description>
    <p>Thunderbird is a full-featured email, RSS and newsgroup client that makes emailing safer, faster and easier than ever before. It supports different mail accounts (POP, IMAP, Gmail), has a simple mail account setup wizard, one- click address book, tabbed interface, an integrated learning spam filter, advanced search and indexing capabilities, and offers easy organization of mails with tagging and virtual folders. It also features unrivalled extensibility.</p>
  </description>
  <pkgname>thunderbird</pkgname>
  <categories>
    <category>Application</category>
    <category>Network</category>
    <category>Email</category>
    <category></category>
  </categories>
  <icon type="cached" width="64" height="64">thunderbird_thunderbird.png</icon>
  <screenshots>
    <screenshot type="default"><caption/><image type="source" width="800" height="600">http://screenshots.ubuntu.com/screenshot/thunderbird</image><image type="thumbnail" width="160" height="120">http://screenshots.ubuntu.com/thumbnail/thunderbird</image></screenshot>
  </screenshots>
</component>
EOF

# Icon according to https://github.com/hughsie/appstream-glib#guidelines-for-applications
mkdir -p usr/share/icons/hicolor/256x256/apps/
cp usr/bin/chrome/icons/default/default256.png usr/share/icons/hicolor/256x256/apps/thunderbird.png

GLIBC_NEEDED=$(glibc_needed)
VERSION=$VER1.glibc$GLIBC_NEEDED
echo $VERSION

get_desktopintegration $LOWERAPP

rm -rf thunderbird

cd ..

ARCH="x86_64"
generate_appimage
