#!/bin/bash -x

# We do not have to build this ourselves since the upstream project 
# does a great job in providing binaries that run on a great number of systems
# other upstream projects could learn from Mozilla - how do they do it?

set +e

mkdir -p ./Firefox/Firefox.AppDir
cd ./Firefox

wget -c --trust-server-names "https://download.mozilla.org/?product=firefox-latest&os=linux64"
VERSION=$(ls firefox-*.tar.bz2 | cut -d "-" -f 2 | sed -e 's|.tar.bz2||g')

cd ./Firefox.AppDir
tar xfj ../*.tar.bz2

mkdir usr
mv firefox usr/bin

find . -name default48.png -exec mv \{\} firefox.png \;

cat > firefox.desktop <<EOF
[Desktop Entry]
Name=Firefox
Icon=firefox
Exec=firefox %u
Categories=GNOME;GTK;Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;x-scheme-handler/chrome;video/webm;application/x-xpinstall;
StartupNotify=true
EOF

cat > AppRun <<\EOF
#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
"$HERE"/usr/bin/firefox $@
EOF
chmod a+x AppRun

# Firefox does not ship with appdata yet, so we fetch it from fedora-appstream upstream
mkdir -p usr/share/appdata/
rm usr/share/appdata/firefox.appdata.xml || true
wget -c "https://github.com/hughsie/fedora-appstream/raw/master/appdata-extra/desktop/firefox.appdata.xml" -O usr/share/appdata/firefox.appdata.xml

cd ..

wget -c "https://github.com/probonopd/AppImageKit/releases/download/4/AppImageAssistant" # 64-bit

mkdir -p ../out/
rm ../out/Firefox-* || true
chmod a+x ./AppImageAssistant
./AppImageAssistant ./Firefox.AppDir/ ../out/Firefox-$VERSION-x86_64.AppImage
