name: Build and Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ${{ matrix.config.runner }}
    strategy:
      matrix:
        config:
          - runner: ubuntu-20.04
            image: ubuntu:20.04
          - runner: ubuntu-22.04-arm
            image: ubuntu:22.04
    container:
      image: ${{ matrix.config.image }}
      options: --privileged
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print configuration
      run: echo "Running build on ${{ matrix.config }}"

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y sudo libarchive-tools curl zsync squashfs-tools aria2 desktop-file-utils wget fuse binutils file imagemagick

    - name: Build and Release
      run: |
           bash -ex dogfeeding.sh
           wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
           bash upload.sh ./out/pkg2appimage*.AppImage*
